[theme]
primaryColor = "#1976D2"       # Bleu moderne (titres, boutons)
backgroundColor = "#CECBCB"    # Fond principal clair
secondaryBackgroundColor = "#56B0FB"  # Fond de la sidebar
textColor = "#212121"          # Texte principal foncé
font = "sans serif"            # Police épurée (Segoe UI, Helvetica...)

#[server]
#headless = true
#enableCORS = false


#[client]
#showSidebarNavigation = true
