[theme]
primaryColor = "#1976D2"       # Bleu moderne (titres, boutons)
backgroundColor = "#FAFAFA"    # Fond principal clair
secondaryBackgroundColor = "#E3F2FD"  # Fond de la sidebar
textColor = "#212121"          # Texte principal foncé
font = "sans serif"            # Police épurée (Segoe UI, Helvetica...)

[server]
headless = true
enableCORS = false


[client]
showSidebarNavigation = true
